# -*- coding: utf-8 -*-
"""S3-Dicionario-NLTK-wordnet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13RLshHOVd5CG4pHVPcuZvErzvMUibEbc

># <b>DICIONÁRIO SIMPLES COM NLTK</b>

> Instituição: PUCPR  
> Curso: Tecnologia em Inteligência Artificial Aplicada  
> Disciplina: Processamento de Linguagem Natural  
> Professor: Lucas Emanuel Silva e Olveira  
> Estudante: Carla Edila Silveira
"""

# Importa bibliotecas NLTK
import nltk
nltk.download('wordnet')
from nltk.corpus import wordnet_ic
from nltk.corpus import wordnet as wn

# Carregando o corpus do WordNet em português
nltk.download('omw-1.4')

# Função para obter definição e frase de exemplo de uma palavra usando WordNet em português
def obter_definicao_e_frase(palavra):
    try:
        synsets = wn.synsets(palavra, lang='por')
        if synsets:
            definicao = synsets[0].definition()
            exemplos = synsets[0].examples()
            frase_exemplo = exemplos[0] if exemplos else ""
            return definicao, frase_exemplo
        else:
            return "Palavra não encontrada no WordNet em português.", ""
    except Exception as e:
        return "Ocorreu um erro ao processar a palavra.", str(e)

# Exemplo de uso
palavra_desejada = input("Digite a palavra que você gostaria de pesquisar: ").lower()
definicao, frase_exemplo = obter_definicao_e_frase(palavra_desejada)

print("\nDefinição:", definicao)
print("Frase de exemplo:", frase_exemplo)

# Busca de sinônimos
print(wn.synsets('room'))

# Busca de definição
syn_arr = wn.synsets('house')
print(syn_arr[0].definition())

# Saída de uma definição em inglês: 'a dwelling that serves as living quarters for one or more families'
# Traduzida como: 'uma habitação que serve de moradia para uma ou mais famílias'

# Busca de sinônimos para 'feliz
synset = wn.synsets('happy')
print('O primeiro sinônimo de HAPPY é: ' + synset[0].lemmas()[0].name())
print('O primeiro sinônimo de HAPPY é: ' + synset[1].lemmas()[0].name())
print('O primeiro sinônimo de HAPPY é: ' + synset[2].lemmas()[0].name())

# Uso do OpenWN-PT, uma wordnet de língua portuguesa
gato_lemmas = wn.lemmas("gato", lang="por")
print (gato_lemmas)

# Busca sinônimos para "celular" e "computador"
celular_synset = wn.synsets('celular', lang='por')
computador_synset = wn.synsets('computador', lang='por')

print(celular_synset)
print(computador_synset)

# Busca de definições para "cellular" e "computer"
syn_arr = wn.synsets('cellular') + wn.synsets('computer')

if syn_arr:
    for syn in syn_arr:
        print(syn.definition())
else:
    print("Nenhuma definição encontrada.")