# -*- coding: utf-8 -*-
"""S4-ATIVIDADE SOMATIVA 1_PLN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-x1SWiCsa3YGPVJc_lcUmDTjBYGrFqd

># <b>ATIVIDADE SOMATIVA 1</b>  
> Instituição: PUCPR  
> Curso: Tecnologia em Inteligência Artifical Aplicada  
> Disciplina: Processamento de Linguagem Natural  
> Professor: Lucas Oliveira  
> Estudante: Carla Edila Silveira  
> Data: 15/04/2024  
>
><img src='https://i.postimg.cc/G2VKsSgc/pln-lord-of-rings.jpg' width=780 height=380>  
><i>Crédito da imagem: gerada com IA Copilot</i>

## <b>Processamento de Linguagem Natural</b>
Resolva os problemas a seguir em equipes de até duas pessoas. A atividade permite consulta ao nosso material e documentação online.

<p align='justify'>Ao professor se reserva o direito de realizar um teste de autoria de quaisquer uma das atividades a seguir, podendo atribuir nota ZERO ao aluno que não corresponder ao teste exigido.</p>

><p align='justify'><b>ATENÇÃO</b>: Não serão aceitas entregas através de links compartilhados do Google Colab. Sua equipe deve entregar um arquivo .ipynb diretamente no AVA (No menu ARQUIVO > FAZER DOWNLOAD você pode criar este arquivo).</p>

Considere o corpus a seguir:
"""

# A seguir um corpus composto por resumos dos primeiros 12 capítulos do livro "Senhor dos Anéis"
# Traduzidos por Luciano Soares e Reinaldo Imrahil - disponível em: https://www.valinor.com.br/82
corpus = [
          "Capítulo 1: Uma festa muito esperada\nSessenta anos passaram desde que Bilbo Bolseiro, o herói de O Hobbit, tinha voltado de sua jornada. Ele é conhecido por muitos, tanto pela sua riqueza legendária como pelo fato de que a idade não parece afetá-lo. Ele anuncia uma grande celebração em honra do 111o aniversário dele e o 33o aniversário do seu sobrinho Frodo, que ele tinha adotado como herdeiro alguns anos atrás e trouxera para viver no Bolsão. A festa estava esplêndida, e um grande número de hobbits foi convidado. Mas Bilbo sentia-se estranho ultimamente, e decidiu que precisava de umas férias e deixaria o Condado; assim, depois de fazer um discurso depois do jantar, na frente dos 144 amigos mais íntimos dele e de Frodo, e também de seus parentes, ele coloca o anel mágico e desaparece, causando grande surpresa. Ele fala mais uma vez com Gandalf antes de partir, e quase muda a sua intenção original de deixar o anel com Frodo; mas o mago o convence a manter a idéia, e Bilbo parte, muito aliviado e mais feliz do que nunca. Gandalf adverte Frodo para não usar o anel. No dia seguinte Frodo está ocupado, pois Bilbo tinha deixado presentes de despedida para muitos hobbits, e agora uma multidão de pessoas se encontra no Bolsão, muitos deles cavando ao redor e procurando os tesouros imaginários de Bilbo. Gandalf parte, e não volta por muito tempo.",
          "Capítulo 2: A Sombra do Passado\nGandalf visita Frodo só algumas vezes pelos anos que seguem. Frodo se acostuma a ser o mestre do Bolsão, e faz amizade com alguns dos hobbits mais jovem [por exemplo com Peregrin Tûk e Merry Brandebuque] enquanto a maioria o considera esquisito, como Bilbo. Rumores de eventos estranhos fora do Condado surgem, como o da ascensão do Poder Escuro na Terra de Mordor, embora a maioria dos hobbits não acreditasse nisso. No qüinquagésimo ano da vida de Frodo, Gandalf o visita novamente e eles têm uma conversa longa sobre o anel que Frodo tinha herdado de Bilbo. Gandalf explica a Frodo a natureza e a história do anel, que é de fato o maior dos Anéis de Poder e foi feito há muito tempo por Sauron, o Senhor do Escuro de Mordor. Sauron o está procurando agora avidamente. Achando o anel o seu poder cresceria imensamente. O anel deveria ser destruído para que Sauron perdesse seu poder, mas só poderia ser destruído em Orodruin, a Montanha da Perdição em Mordor. Parece que Sauron já tinha ouvido falar de Bilbo e do Condado através de Gollum; assim, o Condado provavelmente não é mais um lugar seguro para Frodo. Ele decide partir, acompanhado por Sam Gamgi, o seu jovem jardineiro, que [ao contrário da maioria dos hobbits] acredita nas antigas histórias e adoraria ver os Elfos",
          "Capítulo 3: Três não é demais\nFrodo vende o Bolsão aos Sacola-Bolseiros e compra uma casa na Terra dos Buques, a leste do Condado, onde ele tinha passado sua infância. No seu qüinquagésimo aniversário, ele deixa o Bolsão e parte com seu amigo Pippin [Peregrin Tûk] e Sam Gamgi; Gandalf o deixou por algum tempo para procurar notícias do que acontecia na Terra-média, e ainda não voltou, o que preocupa muito Frodo. No dia seguinte, os três hobbits notam que estão sendo seguidos pelos misteriosos Cavaleiros Negros. Não sabem exatamente quem eles são, e Frodo, cuidadoso, decide não deixar que os Cavaleiros os vejam. Eles conhecem, durante a noite, um grupo vagante de Altos-elfos conduzido por Gildor Inglorion; Frodo fala por muito tempo com Gildor, e o elfo o aconselha a tentar alcançar Valfenda apesar da ausência de Gandalf, e conta-lhe que os Cavaleiros Negros são os perigosos Servos do Inimigo.",
          "Capítulo 4: Um atalho para cogumelos\nNo dia seguinte, Frodo decide pegar um atalho para o rio Brandevin, onde Merry deveria encontrá-los naquele dia; queriam chegar lá mais cedo, e evitar serem vistos novamente pelos Cavaleiros Negros. De fato, eles percebem que um dos Cavaleiros está na estrada e decidem sair dela. Depois de uma passagem longa e desagradável pelos bosques, eles alcançam a propriedade de Fazendeiro Magote, que é conhecido por soltar seus cachorros em qualquer invasor que venha a colher os seus cogumelos [como o próprio Frodo tinha experimentado na sua mocidade]. Contudo, ele é bastante amigável, especialmente por conhecer bastante Pippin; ele conta a Frodo e seus amigos que pouco tempo antes um cavaleiro negro estranho e amedrontador perguntara-lhe por um Bolseiro . Para ajudar Frodo a alcançar a balsa do Brandevin da maneira mais segura e rápida possível, Magote leva os três hobbits com sua carroça , e eles acham Merry esperando-os ansiosamente.",
          "Capítulo 5: Conspiração Desmascarada\nConforme eles cruzam o Rio, notam uma figura negra parada, e cada vez mais próxima. Eles vão para a casa nova de Frodo em Cricôncavo, e falam sobre as suas aventuras na viagem. Frodo pretende falar finalmente para os amigos que vai partir o mais cedo possível quando, para o seu assombro, eles dizem que já sabem sobre o Anel, e sobre o propósito de sua viagem, e que pretendem acompanhá-lo e ajudá-lo. Depois do choque inicial, Frodo aceita a ajuda deles alegremente, e eles decidem partir no dia seguinte, bem cedo, pela Floresta Velha, um lugar conhecido como esquisito e perigoso, para evitar as estradas que provavelmente serão vigiadas pelos Cavaleiros.",
          "Capítulo 6: A Floresta Velha\nOs hobbits entram na Floresta Velha e logo começam a sentir sua estranheza, como se as árvores estivessem vigiando-os e os odiassem. Eles chegam à Clareira onde os hobbits queimaram uma grande quantidade de árvores há muito tempo atrás. De lá, eles seguem um caminho que os conduz a uma colina que sobe fora da Floresta, e de lá, como eles eventualmente notam, para o Rio Withywindle, a parte central e mais estranha da floresta. Eles querem evitar isso e deixar o caminho, mas acham o terreno sempre mais difícil na direção em que gostariam de ir. Eles caem em um barranco que é muito íngreme para ser escalado novamente e, seguindo-o, chegam ao Withywindle e acham um caminho que corre ao longo dele. Este caminho os traz a um velho salgueiro, perto do qual começam a sentir-se sonolentos de repente. Frodo, Merry e Pippin dormem, e a árvore lança Frodo na água e captura Merry e Pippin debaixo de suas raízes. Sam e Frodo não podem salvá-los, e correm ao longo do caminho, enquanto pedem por ajuda, desesperados. Eles encontram Tom Bombadil, um homem estranho que canta canções absurdas. Tom canta a melodia certa, e o salgueiro liberta Merry e Pippin; então Tom convida os hobits para irem à casa dele, onde vive com Fruta DOuro.",
          "Capítulo 7: Na Casa de Tom Bombadil\nEles comem um jantar magnífico e então vão dormir, e cada um deles tem sonhos diferentes e estranhos. No dia os hobbits falam com Tom Bombadil durante o dia inteiro. Tom lhes fala muito sobre a Floresta, os tipos de árvores e animais, o Velho Homem-Salgueiro, e a história antiga da Terra-média, embora de maneira enigmática. Para a surpresa deles, descobrem que o Anel não tem nenhum poder sobre Bombadil. Ele lhes dá conselhos no dia seguinte, e lhes ensina uma rima parra chamá-lo se eles precisarem da ajuda dele.",
          "Capítulo 8: Névoa nas Colinas dos Túmulos\nNo dia seguinte, os hobbits deixam a casa de Tom, pretendendo cruzar os Túmulos. Eles fazem um progresso bom pela manhã, e ao redor de meio-dia param para descansar. Estranhamente há um grande pedra fria que se levanta no topo plano de uma colina. Eles adormecem e são despertados por um pôr-do-sol cercado pela névoa. Eles imediatamente se encaminham na direção que eles acreditam ser a mais direta para a Estrada; algum tempo depois Frodo, que estava na frente, passa entre duas pedras paradas e nota que os outros se foram. Ele começa a gritar por ajuda, e é capturado por uma Criatura Tumular. Ele desperta novamente dentro de um túmulo, nota que os outros estão inconscientes perto dele e que uma mão está rastejando na direção deles. Frodo canta a rima que Tom Bombadil tinha lhes ensinado um dia antes, e realmente Tom vem muito rápido, e a luz do dia destrói a Criatura Tumular. Tom desperta os outros três hobits, e dá a cada um deles uma espada, tirada dos tesouros que estavam dentro do túmulo. Ele também traz os pôneis deles que fugiram à noite, e os acompanha durante algum tempo, até as fronteiras das terras dele. Os hobbits partem, e chegam à aldeia de Bri pela noite.",
          "Capítulo 9: No Pônei Saltitante\nO hobbits entram no Pônei Saltitante, uma hospedaria grande em Bri. Um grupo diversificado de hóspedes já esta reunido lá: hobbits locais e homens, anões em viagem, homens estranhos do Sul, e um Guardião misterioso conhecido como Passolargo. Depois da ceia, Frodo, Sam e Pippin decidem unir-se aos hóspedes; Pippin chama a atenção contando uma história sobre o Prefeito do Condado e, empolgado, começa a contar sobre a festa de despedida de Bilbo. Frodo não quer mencionar o desaparecimento de Bilbo, e para interromper Pippin salta sobre uma mesa e começa a cantar e dançar. Ele salta e cai da mesa, e enquanto cai o Anel desliza para o dedo dele, e ele desaparece. Isto causa muita ansiedade, e apesar das explicações posteriores a maioria dos hóspedes deixa o aposento. Passolargo parece saber o real nome de Frodo, e a verdadeira causa do seu desaparecimento, e lhe pede que tenham uma conversa depois. Carrapicho, o estalajadeiro, também se lembra de algo e pede para ter uma conversa particular com Frodo.",
          "Capítulo 10: Passolargo\nPassolargo vai falar com Frodo, Sam e Pippin. Ele se oferece para ser o guia deles, e parece já saber muito de Frodo; porém, por causa da sua aparência, os hobbits não confiam nele. Então Carrapicho chega e explica que Gandalf tinha deixado uma carta para um certo Frodo Bolseiro, que Carrapicho esquecera de enviar ao Condado há vários meses atrás. Frodo e seus companheiros batem com a descrição que Gandalf dera a Carrapicho, e este dá a carta a Frodo. Entre outras coisas, essa carta contém um conselho de Gandalf para aceitar a ajuda de um amigo seu, um homem chamado Passolargo [com o verdadeiro nome Aragorn], se eles chegassem a conhecê-lo. Assim, Frodo decide aceitar a ajuda dele como um guia para Valfenda. Merry, que saiu para pegar um ar fresco antes, agora volta e conta que viu os Cavaleiros Negros, e parece que eles têm espiões em Bri. Eles decidem não ir para os quartos designados a eles, e dormem no quarto de hóspedes, depois de trancarem as janelas e a porta.",
          "Capítulo 11: Uma Faca no Escuro\nNaquela mesma noite, os Cavaleiros Negros arrombam a casa de Frodo em Cricôncavo, descobrem que Frodo não esta lá, e cavalgam para Bri com grande pressa. Eles arrombam a hospedaria, ou mais especificamente o quarto onde os hóspedes hobbits normalmente dormem. Os hobbits não são descobertos, mas todos os cavalos e pôneis da hospedaria fugiram com medo. No dia seguinte eles compram um pônei e mantimentos [muito mais do que eles poderiam carregar em suas costas]; eles vão em direção a Valfenda, e Passolargo os conduz pela floresta para uma colina chamada Topo do Vento, que oferece uma visão de cima de uma área circunvizinha bem grande. Parece que Gandalf tinha estado lá três dias antes deles. Naquela noite eles são atacados por cinco dos Cavaleiros em uma depressão debaixo do Topo do Vento; Frodo não consegue resistir ao desejo de colocar o Anel, e imediatamente depois de fazer isso percebe que ele pode ver os Cavaleiros muito claramente apesar da escuridão. O capitão dos Cavaleiros ataca Frodo, que o golpeia nos pés mas acaba ferido e perde a consciência .",
          "Capítulo 12: Fuga para o Vau\nPassolargo faz o melhor possível para curar Frodo, mas este só poderia receber o tratamento em Valfenda, que eles deveriam alcançar o mais cedo possível. Eles cruzam o Rio Fontegris e, evitando a estrada, caminham pelos ermos e acabam alcançando a região dos trolls onde Bilbo tivera a sua primeira aventura tantos anos atrás. Eles têm que cruzar uma linha de colinas para se pôr mais perto novamente da Estrada, já que a única esperança deles de alcançar Valfenda a tempo é seguir a Estrada que cruza o rio Ruidoságua, ou Bruinen, no vau de Bruinen. Na Estrada eles conhecem Glorfindel, um Senhor Élfico que foi enviado de Valfenda para achá-los e ajudá-los. Eles se aproximam do Vau de Bruinen e são emboscados pelos Cavaleiros Negros. Frodo consegue escapar e cruzar o rio no cavalo de Glorfindel. Então uma grande inundação vem rio abaixo e leva os Cavaleiros."
]

"""#### <p align='justify'>1) Utilize `Expressões Regulares` para remover de cada um dos textos do corpus o cabeçalho dos capítulos (e.g., "*Capítulo 1:*", "*Capítulo 2*:", "*Capítulo 3*:")</p>"""

# Importa módulo "re", necessário para lidar com expressões regulares.
import re

# Define função para remover cabeçalhos dos capítulos usando expressões regulares
def remover_cabecalhos(corpus):
    novo_corpus = []
    for texto in corpus:
        novo_texto = re.sub(r"Capítulo \d+: ", "", texto)
        novo_corpus.append(novo_texto)
    return novo_corpus

# Aplica a função no corpus
corpus_sem_cabecalhos = remover_cabecalhos(corpus)

# Imprime o resultado da remoção
for texto in corpus_sem_cabecalhos:
    print(texto)

"""#### <p align='justify'>2) Compute a quantidade de caracteres, quantidade de palavras, quantidade de palavras únicas e quantidade de sentenças de cada capítulo e apresente em um `DataFrame` da biblioteca pandas.</p>"""

# Importa biblioteca pandas para criar dataframe
import pandas as pd

# Define função para calcular as métricas de texto
def calcular_metricas(texto):
    # Quantidade de caracteres
    caracteres = len(texto)

    # Quantidade de palavras
    palavras = len(texto.split())

    # Quantidade de palavras únicas
    palavras_unicas = len(set(re.findall(r'\b\w+\b', texto.lower())))

    # Quantidade de sentenças
    sentencas = len(re.split(r'[.!?]', texto))

    return caracteres, palavras, palavras_unicas, sentencas

# Cria listas para armazenar métricas de cada capítulo
caracteres_por_capitulo = []
palavras_por_capitulo = []
palavras_unicas_por_capitulo = []
sentencas_por_capitulo = []

# Calcula métricas para cada capítulo
for texto in corpus:
    caracteres, palavras, palavras_unicas, sentencas = calcular_metricas(texto)
    caracteres_por_capitulo.append(caracteres)
    palavras_por_capitulo.append(palavras)
    palavras_unicas_por_capitulo.append(palavras_unicas)
    sentencas_por_capitulo.append(sentencas)

# Cria dataframe do pandas com as métricas
df_metricas = pd.DataFrame({
    'Capítulo': range(1, len(corpus) + 1),
    'Caracteres': caracteres_por_capitulo,
    'Palavras': palavras_por_capitulo,
    'Palavras Únicas': palavras_unicas_por_capitulo,
    'Sentenças': sentencas_por_capitulo
})

# Exibe o dataframe
print(df_metricas)

"""#### <p align='justify'>3) Apresente um gráfico de barras comparando a quantidade de palavras únicas de cada capítulo.</p>"""

# Importa biblioteca pyplot de matplotlib para gerar gráfico de barras
import matplotlib.pyplot as plt

# Define os dados
capitulos = range(1, len(corpus) + 1)
palavras_unicas = palavras_unicas_por_capitulo

# Plota o gráfico de barras
plt.figure(figsize=(10, 6))
plt.bar(capitulos, palavras_unicas, color='navy')
plt.xlabel('Capítulos')
plt.ylabel('Quantidade de Palavras Únicas')
plt.title('QUANTIDADE DE PALAVRAS ÚNICAS POR CAPÍTULO')
plt.xticks(capitulos)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""#### <p align='justify'>4) Imagine que durante o processo de sumarização/tradução dos textos, os dois revisores participantes referenciaram a palavra "hobbits" de maneira errada em algumas partes do texto, colocando a grafia "hobits" no lugar. Faça um programa que utilizando o algoritmo de **distância de Levenshtein**, encontre e imprima em quais capítulos são encontrados os erros de grafia.</p>

SOLUÇÃO COM  `edit.distance()`
"""

# Importa bibliotecas do NLTK
import nltk
nltk.download('punkt')
from nltk.metrics.distance import edit_distance

# Define função para encontrar e imprimir capítulos com erros de grafia
def contar_erros_grafia(corpus):
    # Contador de erros
    erros_por_capitulo = {}

    # Palavra correta
    palavra_correta = "hobbits"

    # Para cada capítulo no corpus
    for i, capitulo in enumerate(corpus, start=1):
        # Faz tokenização e remoção de pontuação
        palavras = nltk.word_tokenize(capitulo.lower())
        palavras = [p for p in palavras if p.isalnum()]

        # Verifica presença da palavra errada
        if "hobits" in palavras:
            # Conta o número de ocorrências da palavra errada no capítulo
            erros_por_capitulo[i] = palavras.count("hobits")

    return erros_por_capitulo

# Chamada da função para contar erros de grafia
erros_por_capitulo = contar_erros_grafia(corpus)

# Imprime número de erros por capítulo
for capitulo, erros in erros_por_capitulo.items():
    print(f"No Capítulo {capitulo} foram encontradas {erros} ocorrência(s) da palavra 'hobits'.")

"""SOLUÇÃO COM A BIBLIOTECA `Levenshtein`"""

# Instala modulo da biblioteca Levenshtein
!pip install Levenshtein

# Importa biblioteca que implementa algoritmo de distância de Levenshtein em Python
import Levenshtein

# Define função para encontrar erros de grafia em cada capítulo
def encontrar_erros_grafia(corpus):
    erros_de_grafia = []
    palavra_correta = "hobbits"
    limite_distancia = 2  # Limite de distância de Levenshtein para considerar um erro de grafia
    for i, texto in enumerate(corpus, start=1):
        if "hobits" in texto:
            palavras = texto.split()
            for j, palavra in enumerate(palavras):
                if Levenshtein.distance(palavra, palavra_correta) < limite_distancia:
                    erros_de_grafia.append((i, j + 1))  # Adiciona o capítulo e o índice da palavra
    return erros_de_grafia

# Encontra erros de grafia nos capítulos
erros = encontrar_erros_grafia(corpus)

# Imprime os resultados encontrados para "hobbit"
if len(erros) > 0:
    print("Erros de grafia encontrados nos seguintes capítulos:")
    for erro in erros:
        print(f"Capítulo {erro[0]}: Palavra na posição {erro[1]}")
else:
    print("Nenhum erro de grafia encontrado.")

"""#### <p align='justify'>5) Remova as stop-words do corpus e mostre os vetores resultantes (com suas palavras correspondentes) do processo de BoW.</p>
> DICA: Você pode utilizar um atributo da própria função <a href='https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html'>CountVectorizer</a>


"""

# Importa biblioteca CountVectorizer do scikit-learn para criar vetores de palavra
from sklearn.feature_extraction.text import CountVectorizer

# Define as stop words
stop_words = ["uma", "um", "de", "para", "com", "no", "na", "e", "o", "a", "os", "as", "em", "por", "se", "do", "da", "dos", "das", "que"]

# Inicializa o CountVectorizer com as stop words
vectorizer = CountVectorizer(stop_words=stop_words)

# Aplica CountVectorizer no corpus
vetores_bow = vectorizer.fit_transform(corpus)

# Obtém palavras correspondentes aos índices no vocabulário
palavras_vocabulario = vectorizer.get_feature_names_out()

# Mostra vetores resultantes com suas palavras correspondentes
for i, vetor in enumerate(vetores_bow):
    print(f"Capítulo {i+1}:")
    for palavra_idx, frequencia in zip(vetor.indices, vetor.data):
        palavra = palavras_vocabulario[palavra_idx]
        print(f"    {palavra}: {frequencia}")
    print()

"""#### <p align='justify'>6) Faça um algoritmo que leia uma palavra do usuário e em seguida mostre o capítulo mais relevante a pesquisa, juntamente ao correspondente valor de pontuação TF-IDF da palavra buscada no documento.</p>"""

# Importa bibliotecas necessárias
from sklearn.feature_extraction.text import TfidfVectorizer # calcula pontuações TF-IDF para cada palavra no texto
import numpy as np # para manipular os arrays resultantes

# Define lista de stop words em português
stop_words_portuguese = [
    "de", "a", "o", "que", "e", "do", "da", "em", "um", "para", "com", "não", "uma", "os",
    "no", "se", "na", "por", "mais", "as", "dos", "como", "mas", "ao", "ele", "das", "à",
    "seu", "sua", "ou", "quando", "muito", "nos", "já", "eu", "também", "só", "pelo", "pela",
    "até", "isso", "ela", "entre", "depois", "sem", "mesmo", "aos", "seus", "quem", "nas",
    "me", "esse", "eles", "você", "essa", "num", "nem", "suas", "meu", "às", "minha", "numa",
    "pelos", "elas", "qual", "nós", "lhe", "deles", "essas", "esses", "pelas", "este", "dele",
    "tu", "te", "vocês", "vos", "lhes", "meus", "minhas", "teu", "tua", "teus", "tuas", "nosso",
    "nossa", "nossos", "nossas", "dela", "delas", "esta", "estes", "estas", "aquele", "aquela",
    "aqueles", "aquelas", "isto", "aquilo", "estou", "está", "estamos", "estão", "estive", "esteve",
    "estivemos", "estiveram", "estava", "estávamos", "estavam", "estivera", "estivéramos", "esteja",
    "estejamos", "estejam", "estivesse", "estivéssemos", "estivessem", "estiver", "estivermos",
    "estiverem", "hei", "há", "havemos", "hão", "houve", "houvemos", "houveram", "houvera",
    "houvéramos", "haja", "hajamos", "hajam", "houvesse", "houvéssemos", "houvessem", "houver",
    "houvermos", "houverem", "houverei", "houverá", "houveremos", "houverão", "houveria",
    "houveríamos", "houveriam", "sou", "somos", "são", "era", "éramos", "eram", "fui", "foi",
    "fomos", "foram", "fora", "fôramos", "seja", "sejamos", "sejam", "fosse", "fôssemos", "fossem",
    "for", "formos", "forem", "serei", "será", "seremos", "serão", "seria", "seríamos", "seriam",
    "tenho", "tem", "temos", "tém", "tinha", "tínhamos", "tinham", "tive", "teve", "tivemos",
    "tiveram", "tivera", "tivéramos", "tenha", "tenhamos", "tenham", "tivesse", "tivéssemos",
    "tivessem", "tiver", "tivermos", "tiverem", "terei", "terá", "teremos", "terão", "teria",
    "teríamos", "teriam"
]

# Inicializa o TfidfVectorizer com lista de stop words em português
vectorizer = TfidfVectorizer(stop_words=stop_words_portuguese)

# Aplica TfidfVectorizer ao corpus
vetores_tfidf = vectorizer.fit_transform(corpus)

# Pede ao usuário para inserir a palavra que deseja pesquisar
palavra = input("Digite a palavra que deseja pesquisar: ")

# Encontra o índice da palavra no vocabulário
indice_palavra = vectorizer.vocabulary_.get(palavra)

# Se a palavra não estiver no vocabulário, informa ao usuário e encerra
if indice_palavra is None:
    print("A palavra pesquisada não foi encontrada no corpus.")
    exit()

# Calcula pontuação TF-IDF da palavra em cada capítulo
pontuacao_tfidf = vetores_tfidf[:, indice_palavra]

# Encontra capítulo com maior pontuação TF-IDF para a palavra
cap_mais_relevante = np.argmax(pontuacao_tfidf) + 1
pontuacao_max_tfidf = pontuacao_tfidf.max()

# Mostra capítulo mais relevante e pontuação TF-IDF correspondente
print(f"O capítulo mais relevante para a palavra '{palavra}' é o capítulo {cap_mais_relevante}.")
print(f"A pontuação TF-IDF da palavra '{palavra}' neste capítulo é {pontuacao_max_tfidf}.")

# Saída para palavra "festa":
# O capítulo mais relevante para a palavra 'festa' é o capítulo 1.
# A pontuação TF-IDF da palavra 'festa' neste capítulo é 0.15303368850639534.