# -*- coding: utf-8 -*-
"""S4-Desafio-TF-IDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GfLZAOMp3s_LpV7zA8U-5A5-BT1x9QWB

># <b>Desafio: análise de comentários negativos dos consumidores com TF-IDF</b>  
> Instituição: PUCPR  
> Curso: Tecnologia em Inteligência Artifical Aplicada  
> Disciplina: Processamento de Linguagem Natural  
> Professor: Lucas Oliveira  
> Estudante: Carla Edila Silveira  
> Data: 20/04/2024  

<img src='https://i.postimg.cc/gk88VJqL/avaliacao-cliente.png' width=880>

<p align='justify'>CONTEXTO: Extrair conhecimento de um texto envolve várias etapas. Diversas empresas e organizações têm apostado em aplicar técnicas de inteligência artificial para otimizar seus processos.</p>

<p align='justify'>Nesse contexto, identificar o comportamento do consumidor é fundamental para definir estratégias de mercado. Existem diversas plataformas nas quais os clientes deixam suas reclamações em relação às empresas. As avaliações nessas plataformas servem muitas vezes de referência aos consumidores e aos gestores que planejam estratégias para melhorar a visão da empresa.</p>

><p align='justify'>DESAFIO: Imagine que você foi contratado por uma empresa para analisar os comentários negativos que seus consumidores deixaram em uma plataforma de reclamações. Observe, no arquivo a seguir (<i>comments.txt</i>), os comentários negativos dos consumidores. Como profissional responsável por analisar os dados e considerando o arquivo com as reclamações dos consumidores, seu desafio é aplicar o método TF-IDF utilizando a linguagem Python 3 para extrair características do texto e montar uma matriz com os valores TF-IDF. </p>
"""

# Importa bibliotecas necessárias

import pandas as pd
from google.colab import drive
from sklearn.feature_extraction.text import TfidfVectorizer

# Monta drive para carregar arquivo com comentários negativos
drive.mount('/content/drive')

# Caminho para o arquivo .txt
caminho = '/content/drive/MyDrive/Colab Notebooks/Data/comments.txt'

# Leitura do arquivo .txt
with open(caminho, 'r') as file:
    comments = file.readlines()

print(comments)

# Aplica o método TF-IDF
tfidf_vectorizer = TfidfVectorizer(max_features=1000)  # Defina o número máximo de features
tfidf_matrix = tfidf_vectorizer.fit_transform(comments)

# Cria dataframe para visualização dos resultados
feature_names = tfidf_vectorizer.get_feature_names_out()
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)

# Visualiza a matriz TF-IDF
print(tfidf_df)

"""> Gabarito do desafio disponível [aqui]()."""