# -*- coding: utf-8 -*-
"""S4-Desafio-BagOfWords-com-comentarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHd36lKohBPDDgEjJb_1AOCUWPj-4arO

><b> DESAFIO: EXTRAÇÃO DE CARACTERÍSTICAS DE UM TEXTO COM BAG OF WORDS</b>  
>Instituição: PUCPR  
>Curso: Tecnologia em Inteligência Artifical Aplicada  
>Disciplina: Processamento de Linguagem Natural  
>Professor: Lucas Oliveira  
>Estudante: Carla Edila Silveira  
>Data: 15/04/2024  

<p align='justify'>INTRODUÇÃO: Extrair conhecimento de um texto envolve várias etapas. Diversas empresas e organizações têm apostado em aplicar técnicas de inteligência artificial para otimizar seus processos. Nesse contexto, identificar o comportamento do consumidor é fundamental para definir estratégias de mercado. Nos sites de e-commerce, é comum os consumidores registrarem suas avaliações acerca dos produtos adquiridos. Identificar e analisar essas avaliações podem fornecer conhecimentos importantes para as empresas.</p>

Imagine que você foi contratado por uma empresa que vende notebooks.   

<img src='https://i.postimg.cc/fT9CZsNY/notebook-bagofwords.jpg' width=880 height=560>

Veja os comentários:  
<p align='justify'><i>Bom para quem quer realizar tarefas do dia a dia, trabalho, estudo...para isto é ideal. Bem fino, confortável de usar e é bem equipado na sua composição de memoria, armazenamento, processador...fiquei satisfeito. Foi um presente.produto bom, depois que troquei a ram por uma de 08gb e a hd de 1tb por um ssd de 500g ficou um avião, normalmente ligava em quase 02 minutos, agora liga em 08 segundos, o que facilita é a troca dos mesmos, muito simples, sem a necessidade de abri-lo por completo. todo notebook precisa de upgrade para satisfazer, roda
até alguns jogos tranquilamente agora. A entrega foi realizada no prazo, e o produto surpreendeu minhas expectativas.Produto bom, preço acessível. Material com bom acabamento.Leve e bem prático para carregar. Bom. O produto vem atendendo minhas necessidades, como estudo e trabalho do cotinano. O design é lindo e o som, show de bola. Ele consegue ficar umas 3h30 sem tomada. Gostei muito, cumpre o que promete, entrega antes do esperado também. Notebook leve e sem reclamações.Eu adorei chegou bem antes do esperado comprei no dia 28 e
chegou dia 31. Agora é testar!</i></p>  

><p align='justify'><b>DESAFIO: Diante dessa situação, você deve aplicar o algoritmo <i>bag of words</i>, utilizando a linguagem Python para extrair características do texto. Essas características serão usadas futuramente como entrada para algoritmos de aprendizagem de máquina.</b></p>  

​​​​​​​<p align='justify'> Para facilitar a compreensão da solução proposta para este desafio, ao implementar o método <i>bag of words</i> utilizando apenas a linguagem Python, é possível separar os passos em métodos no código. Dessa forma, cria-se um método para: criação do vocabulário, extração de tokens e geração do texto vetorizado, conforme o código que segue.</p>
"""

# Importa bibliotecas necessárias
import re
import numpy

# Cria vocabulário
def word_extraction(sentence):
  ignore = ['a', "do", "é", "e", "na", "um", "que", "de", "por", "em", "o", "no", "dos", "uma", "umas", "para"]
  palavras = re.sub("[^\w]", " ",  sentence).split()
  texto_limpo = [w.lower() for w in palavras if w not in ignore]
  return texto_limpo

# Extrai os tokens
def tokenize(sentences):
  palavras = []
  for sentence in sentences:
    w = word_extraction(sentence)
    palavras.extend(w)
    palavras = sorted(list(set(palavras)))
    return palavras

# Gera a Bag of Words
def generate_bag_of_words(allsentences):
  vocab = tokenize(allsentences)
if __name__ == "__main__":
  texto = "Bom para quem quer realizar tarefas do dia a dia, trabalho, estudo...para isto é ideal. Bem fino, confortável de usar e é bem equipado na sua composição de memoria, armazenamento, processador...fiquei satisfeito. Foi um presente.produto bom, depois que troquei a ram por uma de 08gb e a hd de 1tb por um ssd de 500g ficou um avião, normalmente ligava em quase 02 minutos, agora liga em 08 segundos, o que facilita é a troca dos mesmos, muito simples, sem a necessidade de abri-lo por completo. todo notebook precisa de upgrade para satisfazer, roda até alguns jogos tranquilamente agora. A entrega foi realizada no prazo, e o produto surpreendeu minhas expectativas.Produto bom, preço acessível. Material com bom acabamento.Leve e bem prático para carregar. Bom. O produto vem atendendo minhas necessidades, como estudo e trabalho do cotinano. O design é lindo e o som, show de bola. Ele consegue ficar umas 3h30 sem tomada. Gostei muito, cumpre o que promete, entrega antes do esperado também. Notebook leve e sem reclamações.Eu adorei chegou bem antes do esperado comprei no dia 28 e chegou dia 31. Agora é testar!"

  comentarios = [
        "Bom para quem quer realizar tarefas do dia a dia, trabalho, estudo...para isto é ideal. Bem fino, confortável de usar e é bem equipado na sua composição de memoria, armazenamento, processador...fiquei satisfeito. Foi um presente.",
        "produto bom, depois que troquei a ram por uma de 08gb e a hd de 1tb por um ssd de 500g ficou um avião, normalmente ligava em quase 02 minutos, agora liga em 08 segundos, o que facilita é a troca dos mesmos, muito simples, sem a necessidade de abri-lo por completo. todo notebook precisa de upgrade para  satisfazer, roda até alguns jogos tranquilamente agora.",
        "A entrega foi realizada no prazo, e o produto surpreendeu minhas expectativas.",
        "Produto bom, preço acessível. Material com bom acabamento.Leve e bem prático para carregar. Bom.",
        "O produto vem atendendo minhas necessidades, como estudo e trabalho do cotinano. O design é lindo e o som, show de bola. Ele consegue ficar umas 3h30 sem tomada.",
        "Gostei muito, cumpre o que promete, entrega antes do esperado também. Notebook leve e sem reclamações.",
        "Eu adorei chegou bem antes do esperado comprei no dia 28 e chegou dia 31. Agora é testar!"
  ]
  vocabulario = word_extraction(texto) # resultado é uma lista de palavras únicas que formam o vocabulário do corpus
  tokens = tokenize(vocabulario) #  tokeniza o texto conforme a necessidade
  generate_bag_of_words(comentarios) # função gerar a representação Bag of Words para cada comentário

  for comentario in comentarios:
    palavras = word_extraction(comentario) # extrai palavras únicas do comentário atual
    bag_vector = numpy.zeros(len(vocabulario)) # inicializa vetor de zeros com tamanho do vocabulário, será usado para representar a contagem de palavras no comentário
    for palavra in palavras: # o loop itera sobre cada palavra no comentário atual
      for i,tk in enumerate(vocabulario):
        if tk == palavra:
          bag_vector[i] += 1 # representação Bag of Words do comentário
    print("{0}\n{1}\n".format(comentario,numpy.array(bag_vector))) # imprime comentario e bag_vector

"""ATIVIDADES DIVERSAS
<p align='justify'>-  Para compreender como funciona o CountVectorizer em Python, implementa-se um método, que gera vetores com a frequência de cada
termo e adicion-ae outro método para apresentar os vetores
em uma matriz.</p>  
<img src='https://i.postimg.cc/vDR53gkm/codigo-vetorizador.png'>

"""