# -*- coding: utf-8 -*-
"""S6-teste-exercicio-gensim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HG9cf5oxV3j8wNaZ700-yTuUZa5gDh9N

> # TESTE DE ALGORITMO COM GENSIM  
> Disciplina: Processamento de Linguagem Natural  
> Curso: Tecnologia em Inteligência Artificial Aplicada  
> Professor: Lucas Emanuel de Oliveira  
> Autora: Carla Silveira  
> Data: 08/05/2024  
---
</br>
<p align='justify'>EXERCÍCIO: Modelos pré-treinados permitem que boas representações vetoriais sejam aproveitadas por outros usuários que não teriam acesso a quantidades tão grandes de informação ou não teriam computador rápido o suficiente para executá-las.</p>

<p align='justify'>A partir do modelo pré-treinado em anexo (o arquivo deve ser aberto por um algoritmo usando a função word2vec da biblioteca Gensim), determine qual é a palavra mais próxima da palavra <i>"past"</i> e assinale a opção correta:</p>
</br>  

SOLUÇÃO: O algoritmo para utilizar o modelo deve conter as linhas de comando a seguir.
"""

# Importa bibliotecas necessarias
from gensim.models import Word2Vec
from nltk.corpus import brown

# Carrega modelo Word2Vec previamente treinado
mb = Word2Vec.load('/content/mb.txt')

# Verifica se o modelo foi carregado corretamente
if not isinstance(mb, Word2Vec):
    print("Erro: O arquivo não contém um modelo Word2Vec válido.")
else:
  # Verifica palavras mais similares à palavra 'past'
  similar_words = mb.wv.most_similar('past')
  print("Palavras mais similares a 'past':")
  for word, similarity in similar_words:
    print(f"{word}: {similarity}")